---
title: "S01: Error Real vs Error Computacional"
author: "Alejandro Ucan Puc"
date: "2022-10-26"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Consideraciones:

Trabajaremos con la EDO \[y'=y+t^2+1, \quad 0\leq t\leq 2,\quad y(0)=0.5.\]

* ¿Quién es la constante de Lipschitz? 

* ¿Quién es al solución exacta?

* ¿Quién es la cota para la segunda derivada en $[0,2]$?

> Utilicemos el método de Euler para aproximar la solución de la EDO con $h=0.2.$

```{r}
# Definiremos una rutina llamada Euler, cuyos parametros serán:
# dy.dx=function(x,y){f(t,x,y)}: es la función correspondiente a la derivada, dada por la ecuación diferencial.
# h: es el tamaño de mi paso.
# y0: es mi condición incial.
# start: es el inicio de mi ventana de tiempo/observación.
# end: es el final de mi ventana de tiempo/observación.
Eeuler <- function(dy.dx, y, h=1E-7, y0=1, start=0, end=1) {
nsteps <- (end-start)/h
ys <- numeric(nsteps+1)
yo <- numeric(nsteps+1)
error <- numeric(nsteps+1)
ys[1] <- y0
yo[1] <- y0
error[1] <- abs(ys[1]-yo[1])
for (i in 1:nsteps) {
x <- start + (i-1)*h
ys[i+1] <- ys[i] + h*dy.dx(x,ys[i])
auxx <- start+i*h
yo[i+1] <- y(auxx)
error[i+1] <- abs(ys[i+1]-yo[i+1])
}
return(error)
}
```


```{r}
dy.dx <- function(x,y){y-x^2+1}
y <- function(x){(x+1)^2-(exp(x))/2}
Error<-Eeuler(dy.dx, y, start=0.0, end=2.0, h=0.2, y0=0.5)
Error
```


```{r}
Cerror<- function(h=0.2,L=1,M=0.2,start=0.0,end=2.0){
nsteps <- (end-start)/h
error <- numeric(nsteps+1)
error[1] <- abs(0.0)
for (i in 1:nsteps) {
x <- start + i*h
error[i+1]<-(h*M*exp(L*(x-start)-1))/(2*L)
}
return(error)
}  
```

```{r}
M <- 0.5*exp(2)-2
Cerror(h=0.2,L=1,M=M,start=0,end=2)
```

