---
title: 'S03: Orden de los Métodos'
author: "Alejandro Ucan Puc"
date: "2022-11-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tabla del Orden:
 
 \[
 \begin{array}{ccccc} 
 \hline
 \mbox{Método} & \mbox{Euler} & \mbox{Euler Modificado} & \mbox{RK4} \\ \hline
 \mbox{Evaluaciones por paso} & 1 & 2 & 4 \\ \hline
 \mbox{Orden del Error} & O(h) & O(h^2) & O(h^4)
 \end{array}
\]

### Ejemplo:

Consideremos la ecuación anterior $$y'=y-t^2+1, \quad 0\leq t\leq 2, \quad y(0)=0.5$$

Calcularemos las aproximación con el método de Euler (tamaño de paso $h=0.025$), Euler modificado (tamaño de paso $h=0.05$) y Runge-Kutta de orden 4 (tamaño de paso $h=0.1$).

```{r}
euler <- function(dy.dx, h=1E-7, y0=1, start=0, end=1) {
nsteps <- (end-start)/h
ys <- numeric(nsteps+1)
ys[1] <- y0
for (i in 1:nsteps) {
x <- start + (i-1)*h
ys[i+1] <- ys[i] + h*dy.dx(x,ys[i])
}
return(ys)
}

Modeuler <-function(dy.dx, h=1E-7, y0=1, start=0, end=1){
nsteps <- (end-start)/h
n <- numeric(nsteps+1)
ys <- numeric(nsteps+1)
ys[1] <- y0
for (i in 1:nsteps) {
x <- start + (i-1)*h
auxy <- ys[i] + h*dy.dx(x,ys[i])
ys[i+1] <- ys[i] + h*(dy.dx(x,ys[i])+dy.dx(x+h,auxy))/2
}
return(ys)
}

rk4 <- function(dy.dx, h=1E-7,y0=1,start=0,end=1){
nsteps <- (end-start)/h
n <- numeric(nsteps+1)
ys <- numeric(nsteps+1)
ys[1] <- y0
for (i in 1:nsteps){
  x <- start + (i-1)*h
  k1=h*dy.dx(x,ys[i])
  k2=h*dy.dx(x+h/2.0,ys[i]+k1/2.0)
  k3=h*dy.dx(x+h/2.0,ys[i]+k2/2.0)
  k4=h*dy.dx(x+h,ys[i]+k3)
  ys[i+1] <- ys[i]+(k1+2.0*k2+2.0*k3+k4)/6.0
}
return(ys)
}
```

```{r}
dy.dx <- function(x,y){y-x^2+1}
y <- function(x){(x+1)^2-0.5*(exp(x))}
yE<- euler(dy.dx,h=0.025,y0=0.5,start=0.0,end=2.0)
yEM <- Modeuler(dy.dx, h=0.05,y0=0.5,start=0.0,end=2.0)
yRK4 <- rk4(dy.dx,h=0.1,y0=0.5,start=0.0,end=2.0)
```

```{r}
nsteps <- (2.0)/0.025
yo <-numeric(nsteps+1)
for (i in 0:nsteps){
  x=0.0+i*0.25
  yo[i]<-y(x)
}

cat('y-Orginal', yo)
cat('y-Euler', yE)
cat('y-EulerMod',yEM)
cat('y-RK4',yRK4)
```



