---
title: "S07: Diferencias Finitas en R"
author: "Alejandro Ucan Puc"
date: "2022-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Utilizaremos el paquete ReacTran

```{r}
install.packages("ReacTran")
require(ReacTran)
```


```{r}
Nx <- 4
Ny <- 4
xgrid <- setup.grid.1D(x.up=0, x.down = 0.5, N=Nx)
ygrid <- setup.grid.1D(x.up=0,x.down = 0.5, N=Ny)

x <- xgrid$x.mid
y <- ygrid$x.mid

poisson <- function(t, U, parms) {
  w <- matrix(nrow = Nx, ncol = Ny, data = U)
  dw <- tran.2D(C=w, C.x.up=0, C.x.down = 200*x, flux.y.up = 0, flux.y.down = 200*x,D.x = 1, D.y=1, dx=xgrid, dy=ygrid)$dC
  list(dw)
}
#print(system.time(
  out <- steady.2D(y=runif(Nx*Ny),func=poisson, parms=NULL, nspec=1, dimens=c(Nx,Ny),lrw=1e7)
#))

w<- matrix(nrow=Nx, ncol=Ny, data=out$y)

#analytic <- function(x,y){sin(pi*x)*cosh(pi*y)}
#outana<- outer(x,y,FUN=analytic)
cat(w)
#max(abs(w-outana))

image(out,grid=list(x,y),main="Elliptic Laplace", add.contour=TRUE)
```


```{r}
Nx <- 6
Ny <- 5
xgrid <- setup.grid.1D(x.up=0, x.down = 2, N=Nx)
ygrid <- setup.grid.1D(x.up=0,x.down = 1, N=Ny)

x <- xgrid$x.mid
y <- ygrid$x.mid

poisson <- function(t, U, parms) {
  w <- matrix(nrow = Nx, ncol = Ny, data = U)
  dw <- tran.2D(C=w, C.x.up=0, C.x.down = 2*exp(y), flux.y.up = 0, flux.y.down = exp(1)*x,D.x = 1, D.y=1, dx=xgrid, dy=ygrid)$dC
  list(dw)
}
#print(system.time(
  out <- steady.2D(y=runif(Nx*Ny),func=poisson, parms=NULL, nspec=1, dimens=c(Nx,Ny),lrw=1e7)
#))

w<- matrix(nrow=Nx, ncol=Ny, data=out$y)

#analytic <- function(x,y){sin(pi*x)*cosh(pi*y)}
#outana<- outer(x,y,FUN=analytic)
cat(w)
#max(abs(w-outana))

image(out,grid=list(x,y),main="Elliptic Laplace", add.contour=TRUE)
```

